# Generated by Django 5.1.3 on 2024-11-18 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_point', models.CharField(max_length=255)),
                ('end_point', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('stop_point', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('user_email', models.EmailField(max_length=255, unique=True)),
                ('hashed_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('comment', models.TextField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='we_app.route')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='we_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteRoutes',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='we_app.route')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='we_app.user')),
            ],
        ),
    ]
