# Generated by Django 5.1.4 on 2025-01-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
