# Generated by Django 5.1.2 on 2025-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0002_remove_routehistory_route_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='user_id',
        ),
        migrations.AddField(
            model_name='route',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
