# Generated by Django 5.1.4 on 2025-01-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
