# Generated by Django 5.1.4 on 2025-01-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0004_remove_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='nickname',
        ),
    ]
