# Generated by Django 5.1.2 on 2025-01-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0004_alter_route_endpoint_alter_route_start_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='endpoint',
            new_name='mainWaypoints',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='start_point',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='route',
            name='waypoints',
        ),
    ]
